# Generated by Django 3.2.8 on 2022-01-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_github',
            new_name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
    ]
