# Generated by Django 3.2.8 on 2022-01-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220114_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_linkedin',
        ),
    ]
