# Generated by Django 3.2.8 on 2022-01-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='vote_total',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='featured_image',
            field=models.ImageField(blank=True, default='athlete-default.png', null=True, upload_to=''),
        ),
    ]
