# Generated by Django 3.2.8 on 2022-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20220103_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='athlete',
            name='sponsors',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
