# Generated by Django 3.2.8 on 2022-01-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20220103_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='highlight_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sponsor_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sponsor_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sponsor_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sponsor_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sponsor_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
