# Generated by Django 3.2.8 on 2022-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20220110_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sponsor_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
