# Generated by Django 3.2.8 on 2022-01-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_alter_athlete_sponsor_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
