# Generated by Django 3.2.8 on 2022-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_athlete_social_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
