# Generated by Django 3.2.8 on 2022-01-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_athlete_social_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='social_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
