# Generated by Django 3.2.8 on 2022-01-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0011_athlete_social_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
